// <auto-generated />
using System;
using Joobie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Joobie.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200127003427_databaseRecords")]
    partial class databaseRecords
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Joobie.Models.JobModels.CVJobApplicationUser", b =>
                {
                    b.Property<long>("JobInMiddleTableId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmployeeUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CvName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobInMiddleTableId", "EmployeeUserId");

                    b.HasIndex("EmployeeUserId");

                    b.ToTable("CVJobApplicationUser");
                });

            modelBuilder.Entity("Joobie.Models.JobModels.Category", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "Administracja biurowa"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "Doradztwo / Konsulting"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "Badania i rozwój"
                        },
                        new
                        {
                            Id = (byte)4,
                            Name = "Bankowość"
                        },
                        new
                        {
                            Id = (byte)5,
                            Name = "BHP / Ochrona środowiska"
                        },
                        new
                        {
                            Id = (byte)6,
                            Name = "Budownictwo"
                        },
                        new
                        {
                            Id = (byte)7,
                            Name = "Call Center"
                        },
                        new
                        {
                            Id = (byte)8,
                            Name = "Edukacja / Szkolenia"
                        },
                        new
                        {
                            Id = (byte)9,
                            Name = "Finanse / Ekonomia"
                        },
                        new
                        {
                            Id = (byte)10,
                            Name = "Franczyzna / Własny biznes"
                        },
                        new
                        {
                            Id = (byte)11,
                            Name = "Hotelarstwo / Gastronomia / Turystyka"
                        },
                        new
                        {
                            Id = (byte)12,
                            Name = "Human Resources / Zasoby ludzkie"
                        },
                        new
                        {
                            Id = (byte)13,
                            Name = "Internet / e-Commerce / Nowe media"
                        },
                        new
                        {
                            Id = (byte)14,
                            Name = "Inżynieria"
                        },
                        new
                        {
                            Id = (byte)15,
                            Name = "IT - Administracja"
                        },
                        new
                        {
                            Id = (byte)16,
                            Name = "IT - Rozwój oprogramowania"
                        },
                        new
                        {
                            Id = (byte)17,
                            Name = "Łańcuch dostaw"
                        },
                        new
                        {
                            Id = (byte)18,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = (byte)19,
                            Name = "Media / Sztuka / Rozrywka"
                        },
                        new
                        {
                            Id = (byte)20,
                            Name = "Nieruchomości"
                        },
                        new
                        {
                            Id = (byte)21,
                            Name = "Obsługa klienta"
                        },
                        new
                        {
                            Id = (byte)22,
                            Name = "Praca fizyczna"
                        },
                        new
                        {
                            Id = (byte)23,
                            Name = "Prawo"
                        },
                        new
                        {
                            Id = (byte)24,
                            Name = "Produkcja"
                        },
                        new
                        {
                            Id = (byte)25,
                            Name = "Public Relations"
                        },
                        new
                        {
                            Id = (byte)26,
                            Name = "Reklama / Grafika / Kreacja / Fotografia"
                        },
                        new
                        {
                            Id = (byte)27,
                            Name = "Sektor publiczny"
                        },
                        new
                        {
                            Id = (byte)28,
                            Name = "Sprzedaż"
                        },
                        new
                        {
                            Id = (byte)29,
                            Name = "Transport / Spedycja"
                        },
                        new
                        {
                            Id = (byte)30,
                            Name = "Ubezpieczenia"
                        },
                        new
                        {
                            Id = (byte)31,
                            Name = "Zakupy"
                        },
                        new
                        {
                            Id = (byte)32,
                            Name = "Kontrola jakości"
                        },
                        new
                        {
                            Id = (byte)33,
                            Name = "Zdrowie / Uroda / Rekreacja"
                        },
                        new
                        {
                            Id = (byte)34,
                            Name = "Energetyka"
                        },
                        new
                        {
                            Id = (byte)35,
                            Name = "Inne"
                        });
                });

            modelBuilder.Entity("Joobie.Models.JobModels.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AddedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<byte>("CategoryId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpirationDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Localization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("TypeOfContractId")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("WorkingHoursId")
                        .HasColumnType("tinyint");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TypeOfContractId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkingHoursId");

                    b.ToTable("Job");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AddedDate = new DateTime(2020, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = (byte)16,
                            Description = ":)",
                            ExpirationDate = new DateTime(2020, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localization = "Gdańsk",
                            Name = ".NET Developer",
                            Salary = "5000",
                            TypeOfContractId = (byte)1,
                            UserId = "31d98481-9339-4e36-b3d4-c8f7e7ab3256",
                            WorkingHoursId = (byte)1,
                            isActive = true
                        },
                        new
                        {
                            Id = 2L,
                            AddedDate = new DateTime(2020, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = (byte)1,
                            Description = ":)",
                            ExpirationDate = new DateTime(2020, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localization = "Gdynia",
                            Name = "Junior .NET Developer",
                            Salary = "5300",
                            TypeOfContractId = (byte)1,
                            UserId = "31d98481-9339-4e36-b3d4-c8f7e7ab3256",
                            WorkingHoursId = (byte)2,
                            isActive = true
                        },
                        new
                        {
                            Id = 3L,
                            AddedDate = new DateTime(2020, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = (byte)1,
                            Description = ":)",
                            ExpirationDate = new DateTime(2020, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localization = "Sopot",
                            Name = "Senior .NET Developer",
                            Salary = "4000",
                            TypeOfContractId = (byte)1,
                            UserId = "31d98481-9339-4e36-b3d4-c8f7e7ab3256",
                            WorkingHoursId = (byte)1,
                            isActive = true
                        },
                        new
                        {
                            Id = 4L,
                            AddedDate = new DateTime(2020, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = (byte)16,
                            Description = ":)",
                            ExpirationDate = new DateTime(2020, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localization = "Koszalin",
                            Name = "Starszy Inżynier Oprogramowania .NET",
                            Salary = "5000",
                            TypeOfContractId = (byte)1,
                            UserId = "31d98481-9339-4e36-b3d4-c8f7e7ab3256",
                            WorkingHoursId = (byte)1,
                            isActive = true
                        },
                        new
                        {
                            Id = 5L,
                            AddedDate = new DateTime(2020, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = (byte)16,
                            Description = ":)",
                            ExpirationDate = new DateTime(2020, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localization = "Warszawa",
                            Name = "Programista .NET",
                            Salary = "5900",
                            TypeOfContractId = (byte)1,
                            UserId = "31d98481-9339-4e36-b3d4-c8f7e7ab3256",
                            WorkingHoursId = (byte)3,
                            isActive = true
                        },
                        new
                        {
                            Id = 6L,
                            AddedDate = new DateTime(2020, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = (byte)16,
                            Description = ":)",
                            ExpirationDate = new DateTime(2020, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localization = "Gdańsk",
                            Name = "C# .Net developer",
                            Salary = "200",
                            TypeOfContractId = (byte)3,
                            UserId = "31d98481-9339-4e36-b3d4-c8f7e7ab3256",
                            WorkingHoursId = (byte)1,
                            isActive = true
                        },
                        new
                        {
                            Id = 7L,
                            AddedDate = new DateTime(2020, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = (byte)15,
                            Description = ":)",
                            ExpirationDate = new DateTime(2020, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localization = "Lębork",
                            Name = ".NET Developer",
                            Salary = "6000",
                            TypeOfContractId = (byte)5,
                            UserId = "31d98481-9339-4e36-b3d4-c8f7e7ab3256",
                            WorkingHoursId = (byte)1,
                            isActive = true
                        },
                        new
                        {
                            Id = 8L,
                            AddedDate = new DateTime(2020, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = (byte)12,
                            Description = ":)",
                            ExpirationDate = new DateTime(2020, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localization = "Gdańsk",
                            Name = ".NET Developer",
                            Salary = "9000",
                            TypeOfContractId = (byte)3,
                            UserId = "31d98481-9339-4e36-b3d4-c8f7e7ab3256",
                            WorkingHoursId = (byte)1,
                            isActive = true
                        },
                        new
                        {
                            Id = 9L,
                            AddedDate = new DateTime(2020, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = (byte)13,
                            Description = ":)",
                            ExpirationDate = new DateTime(2020, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localization = "Gdańsk",
                            Name = "Software Engineer C#",
                            Salary = "5300",
                            TypeOfContractId = (byte)3,
                            UserId = "31d98481-9339-4e36-b3d4-c8f7e7ab3256",
                            WorkingHoursId = (byte)3,
                            isActive = true
                        },
                        new
                        {
                            Id = 10L,
                            AddedDate = new DateTime(2020, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = (byte)11,
                            Description = ":)",
                            ExpirationDate = new DateTime(2020, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localization = "Gdynia",
                            Name = "Quality Assurance",
                            Salary = "5300",
                            TypeOfContractId = (byte)1,
                            UserId = "31d98481-9339-4e36-b3d4-c8f7e7ab3256",
                            WorkingHoursId = (byte)3,
                            isActive = true
                        },
                        new
                        {
                            Id = 11L,
                            AddedDate = new DateTime(2020, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = (byte)15,
                            Description = ":)",
                            ExpirationDate = new DateTime(2020, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localization = "Gdańsk",
                            Name = "Programista .NET",
                            Salary = "3333",
                            TypeOfContractId = (byte)5,
                            UserId = "31d98481-9339-4e36-b3d4-c8f7e7ab3256",
                            WorkingHoursId = (byte)1,
                            isActive = true
                        },
                        new
                        {
                            Id = 12L,
                            AddedDate = new DateTime(2020, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = (byte)16,
                            Description = ":)",
                            ExpirationDate = new DateTime(2020, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localization = "Gdańsk",
                            Name = "Junior .NET Developer",
                            Salary = "5300",
                            TypeOfContractId = (byte)5,
                            UserId = "31d98481-9339-4e36-b3d4-c8f7e7ab3256",
                            WorkingHoursId = (byte)2,
                            isActive = true
                        },
                        new
                        {
                            Id = 13L,
                            AddedDate = new DateTime(2020, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = (byte)16,
                            Description = ":)",
                            ExpirationDate = new DateTime(2020, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localization = "Gdańsk",
                            Name = "Azure DevOps",
                            Salary = "4300",
                            TypeOfContractId = (byte)1,
                            UserId = "31d98481-9339-4e36-b3d4-c8f7e7ab3256",
                            WorkingHoursId = (byte)3,
                            isActive = true
                        });
                });

            modelBuilder.Entity("Joobie.Models.JobModels.TypeOfContract", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeOfContract");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "Umowa o pracę"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "Umowa o dzieło"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "Umowa zlecenie"
                        },
                        new
                        {
                            Id = (byte)5,
                            Name = "Kontrakt B2B"
                        },
                        new
                        {
                            Id = (byte)6,
                            Name = "Umowa na zastępstwo"
                        },
                        new
                        {
                            Id = (byte)7,
                            Name = "Umowa agencyjna"
                        });
                });

            modelBuilder.Entity("Joobie.Models.JobModels.WorkingHours", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkingHours");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "Pełny etat"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "Część etatu"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "Tymczasowa"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Joobie.Models.JobModels.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("CompanyImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "31d98481-9339-4e36-b3d4-c8f7e7ab3256",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e5fbd409-c106-4492-8ed1-deeb2da3a7af",
                            Email = "DefaultUser@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedUserName = "DEFAULTUSER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKQK0227340I7E9mRrWOJJwBpOyDx6zuZ9iN06nmNGJZkEyHl7ZZdBgxhtulSzn69Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "PBSCMSVSUTGUUIVILSKHSXF2HIQ2OXW6",
                            TwoFactorEnabled = false,
                            UserName = "DefaultUser@gmail.com",
                            Name = "DefaultCompany",
                            Nip = "DefaultNip"
                        });
                });

            modelBuilder.Entity("Joobie.Models.JobModels.CVJobApplicationUser", b =>
                {
                    b.HasOne("Joobie.Models.JobModels.ApplicationUser", "EmployeeUser")
                        .WithMany("CVJobApplicationUser")
                        .HasForeignKey("EmployeeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Joobie.Models.JobModels.Job", "JobInMiddleTable")
                        .WithMany("CVJobApplicationUser")
                        .HasForeignKey("JobInMiddleTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Joobie.Models.JobModels.Job", b =>
                {
                    b.HasOne("Joobie.Models.JobModels.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Joobie.Models.JobModels.TypeOfContract", "TypeOfContract")
                        .WithMany()
                        .HasForeignKey("TypeOfContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Joobie.Models.JobModels.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("Joobie.Models.JobModels.WorkingHours", "WorkingHours")
                        .WithMany()
                        .HasForeignKey("WorkingHoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
